version: 2
updates:
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "montly"
      
  - package-ecosystem: "docker"
    directory: "/backend/"
    schedule:
      interval: "montly"
