services:
  nginx:
    ports:
      - 8080:80
      - 443:443
    restart: no

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      tags:
        - crpdl/phpiaca
    env_file:
      - .env
    environment:
      - DEPLOYMENT_MODE=fake
    volumes:
      - type: bind
        source: ./backend
        target: /var/www/html
    restart: no

