services:
  nginx:
    image: nginx:1.27-alpine3.21-slim
    ports:
      #- 80:8080
      - 443:4343
    volumes:
      - type: bind
        source: ./nginx/default-ssl.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./nginx/certs
        target: /etc/nginx/certs
        read_only: true
      - type: bind
        source: ./nginx/static
        target: /var/www/html
        read_only: true
    depends_on:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "wget -q --no-check-certificate --spider nginx:80/nginx-health-check || exit 1" ]
      interval: 60s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
      tags:
        - crpdl/phpiaca
    env_file:
      - .env
    environment:
      - DEPLOYMENT_MODE=ad
      - CocherMDPtmp=${CocherMDPtmp}
      - DECONNEXION_SESSION_INACTIVE=${DECONNEXION_SESSION_INACTIVE?300}
      - URLAideCreation=${URLAideCreation}

      - ACL_AfficherBoutonVoirTous=${ACL_AfficherBoutonVoirTous?NOBODY}
      - ACL_AfficherMenuAide=${ACL_AfficherMenuAide?NOBODY}
      - ACL_AfficherMenuCompteExams=${ACL_AfficherMenuCompteExams?NOBODY}
      - ACL_AfficherMenuJournal=${ACL_AfficherMenuJournal?NOBODY}
      - ACL_AfficherMenuListeTemporaire=${ACL_AfficherMenuListeTemporaire?NOBODY}
      - ACL_AfficherMenuProfilProf=${ACL_AfficherMenuProfilProf?NOBODY}
      - ACL_AfficherPassPhrase=${ACL_AfficherPassPhrase?NOBODY}

      - AD_ServerIP=${AD_ServerIP?Undefined}
      - AD_Chemin=${AD_Chemin?Undefined}
      - AD_Domain=${AD_Domain?Undefined}
      - AD_Grp_Cache=${AD_Grp_Cache?Undefined}
      - AD_OU_ELEVES=${AD_OU_ELEVES?Undefined}
      - AD_OU_EXAMEN=${AD_OU_EXAMEN?Undefined}
      - AD_OU_GURU=${AD_OU_GURU?Undefined}
      - AD_OU_PROF=${AD_OU_PROF?Undefined}
      - AD_UserGest=${AD_UserGest?Undefined}
      - AD_PassGest_FILE=/run/secrets/pw_operator
    secrets:
      - pw_operator
    volumes:
      - type: volume
        source: db-data
        target: /logs
    healthcheck:
      test: [ "CMD-SHELL", "SCRIPT_NAME=/status;SCRIPT_FILENAME=/status;REQUEST_METHOD=GET;", "cgi-fcgi", "-bind", "-connect", "backend:9000" ]
      interval: 60s
      timeout: 10s
      retries: 3

    restart: unless-stopped

volumes:
  db-data:


secrets:
  pw_operator:
    file: ./password.txt
