; Version 2

[Global]

; Mode de fonctionnement de l'application
; choix entre 'ad' pour interroger l'active directory ou 'fake' pour test hors domaine.
mode			= fake

; Duree en secondes de la session avant deconnexion automatique
idletime	= 300

; Cocher par défaut la case 'le mot de passe devra être changé'
CocherMDPtmp = false

; Adresse URL du lien 'Aide pour la création de mots de passes', ne rien mettre pour le masquer
URLAideCreation = https://www.cnil.fr/fr/les-conseils-de-la-cnil-pour-un-bon-mot-de-passe


; Paramètrage pour communiquer avec le serveur du domaine
[AD]

;	Adresse Ip du serveur IACA et controleur du domaine
ServerIP	= "10.144.36.65"

; nom DNS du domaine (utilisé pour se connecter ex: domaine\prof)
Domain		= "Contoso"

; Chemin de la racine LDAP
Chemin		= "dc=Contoso,dc=fr"

; Chemin de l'UO contenant les eleves (sensible à la casse)
OU_ELEVES	= "OU=ELEVES,OU=Users,OU=Site par défaut,OU=IACA,DC=Contoso,DC=fr"

; Chemin de l'UO contenant les profs, ou utilisateurs autorisé a changer des mdps (sensible à la case),
OU_PROF[] = "OU=PROFS,OU=Users,OU=Site par défaut,OU=IACA,DC=Contoso,DC=fr"

; Chemin de l'UO contenant les comptes examens (sensible à la case),
OU_EXAMEN = "OU=EXAMEN,OU=Users,OU=Site par défaut,OU=IACA,DC=Contoso,DC=fr"

; UO ou utilisateur qui est autorisé a configurer cette appli (sensible à la case),
OU_GURU[] = "CN=admin1,OU=ADMINMOD,OU=Users,OU=Site par défaut,OU=IACA,DC=Contoso,DC=fr"

; Liste de groupes classes a ne pas afficher
Grp_Cache[]	= "EXAMEN"
Grp_Cache[]	= "UTILISATEURS PARTICULIERS"
Grp_Cache[]	= "TEST"

; compte utilisateur du domaine (type "opérateur de comptes") autorisé a modifier l'ad
; sert juste pour imposer le changement de mot de passe aux eleves
UserGest = "svc-foobar"
; Mot de passe de l'opérateur de comptes
PassGest = "hCpwJY2ZqUp9228JPMTwkkJQ7nFd3ta"


; Contrôle l'accès aux différentes parties de l'application
; utiliser une des valeurs suivantes : 'TERENCE' (autorise personne), 'ELEVE', 'PROF', 'GURU' (compte admin)
[ACL]

; Accès à l'aide décrivant l'appli
AfficherMenuAide = PROF

; Accès à cete page de configuration
AfficherMenuConfig = PROF

; Accès à la liste des comptes qui n'ont pas encore servit
AfficherMenuListeTemporaire = GURU

; Accès à la page pour générer des comptes examens ou invités
AfficherMenuCompteExams = GURU

; Accès au journal d'evenement
AfficherMenuJournal = PROF

; Accès au profil pour changer son mdp
AfficherMenuProfilProf = ELEVE

; Page générant les étiquettes imprimables (non existante sur la v2)
AfficherBoutonImprimer = TERENCE

; Permettre d'afficher tous les mdp d'une page (inutilisable avec mdp masqués)
AfficherBoutonVoirTous = TERENCE

; Activer le générateur de pass-phrase dans la page profil, et le popup
AfficherPassPhrase = ELEVE

